### ISSUE TITLE
Positive definite matrix error

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer-matlab#12]
Daniel, I'm assigning you this because it's useful to understand urdf files (Universal Robotic Description Files). Also Lukas, this is of interest to you because you can actually load a URDF file in matlab.

https://www.mathworks.com/help/robotics/ref/importrobot.html

Remember to be in the right folder (Soccer_desciption) This is the same folder as the one running on the robot for gazebo.

I think it is because the inertial matrixes have negative numbers in them. Make sure any of the inertial diagonal terms doesn't have negative numbers

https://en.wikipedia.org/wiki/Positive-definite_matrix

![image](https://user-images.githubusercontent.com/2901616/43361523-749e91f4-929e-11e8-8fa8-e4656d004bc0.png)

**Comment by danielcampoverde** [comment]
working 
![image](https://user-images.githubusercontent.com/25035329/43995300-585af57e-9d79-11e8-8689-02af466bd271.png)

**Comment by Vuwij** [comment]
Hey @CainRose I got the load ROS model working, also I've completely updated all the center of masses and moments of inertias correctly this time. See the joint table

https://docs.google.com/spreadsheets/d/1KgIYwm3fNen8yjLEa-FEWq-GnRUnBjyg4z64nZ2uBv8/edit#gid=0

Links V4.1

**Comment by Vuwij** [comment]
Modelling and simulation is a mess, but give this a try
