### ISSUE TITLE
Implement the option to use RRT (Rapidly Exploring Random Trees) 

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer-matlab#14]
Since our humanoid robot cannot explore completely based on finding points, it's better to use an RRT algorithm to find the future path for the robot rather than the existing one. Essentially its basically a Dijkstra algorithm, but continuously expanding

https://www.mathworks.com/matlabcentral/fileexchange/60993-2d-3d-rrt-algorithm

It is suggested that the constraints for the RRT should be that the robot can only perform known actions that we have tested before, so we are sure it is capable of performing these actions. A set list of actions and the destinations they go to should be created in some sort of class.

![b50082ed389d7db95dfa6c68248cacb74d69ce3b](https://user-images.githubusercontent.com/2901616/43687618-2d5bd82a-98a6-11e8-96a1-2fc4774d1f56.png)

**Comment by danielcampoverde** [comment]
Algorithm implemented. Not considering any constraint yet.
