### ISSUE TITLE
4. Setup Docker Environment with the python

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer-matlab#28]
https://blog.codeship.com/using-docker-compose-for-python-development/

**Comment by Justin-Yuan** [comment]
which part do u want to capture in docker? if it's just the soccer-rl (with only a few dependencies) it seems like an overkill.

**Comment by Vuwij** [comment]
Maybe. Maybe wait until dependencies get out of hand and then docker it. Work on motor control for now I guess

Regards, 
Jason Wang, Computer Eng. Student
Tel: 647-879-4660 | Skype: Jaw.vuwij

**Comment by Vuwij** [comment]
Also please annouce what you are doing by creating a new issue so others will k ow what you are doing 

Regards, 
Jason Wang, Computer Eng. Student
Tel: 647-879-4660 | Skype: Jaw.vuwij

**Comment by Vuwij** [comment]
@Justin-Yuan I think another advantage of using Docker is that you can deploy to Amazon EC2 workstations and train remotely. Their computers are way better
