### ISSUE TITLE
Improve the speed of the simulink by using persistent variables instead of feedback loops

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer-matlab#8]
In soccer_strategy.slx > IMU Feedback > some block. I want you to remove the feedback loops and change the feedback loops into persistent variables. Look for the IMU feedback loop, in the variant control which uses a complementary filter. Change it to use persistent variables. Don't forget to test! If you don't have a simulation computer you can use mine on Saturday. Otherwise VM is too slow. You need a seperate computer OR you can use the computer on the robot itself. Which requires a screen. For now don't worry about the screen until we can work in the new lab.

https://www.mathworks.com/help/matlab/ref/persistent.html

**Comment by danielcampoverde** [comment]
persistent variable implemented
